### ISSUE TITLE
Staging: Admin loads 500 error

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#1009]
### Current behavior
Indicators not saving on Staging

admin:
![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/d810e2d3-9a8d-4bbc-b4b5-6ce2ae70228e)

### Expected behavior

Add and Save indicators

**Comment by Menda** [comment]
Missing requirement fixed it:
https://github.com/toladata/ActivityAPI/commit/fbf05e3d14645e8a7d2b6b2c4e6ba78a2a2f0099

**Comment by karrla** [comment]
@Menda                        
500 erroris fixed, but I still can't create/save any indicators

**Comment by Menda** [comment]
OK, then we can close this because for that we have a specific issue opened https://github.com/toladata/ActivityAPI/issues/29
