### ISSUE TITLE
New Users are not being added to the default programs

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#1016]
### Current behavior
New Users are not being added to the default programs

### Expected behavior
see closed ticket: #641
All Demo Users should have Workflow Teams access to the default WFL1:
Humanitarian Response to the Syrian Crisis
/activity/programs/3

with the Workflow Team - Role =ViewOnly
/admin/workflow/workflowteam/add/

### Steps to reproduce the behavior

1. Register new user
2. Log in to Activity
3. WFL1 list is empty

### Additional details
related to closed: #639

**Comment by Menda** [comment]
Someone changed the default program name to `AID Humanitarian Response to the Syrian Crisis`. For security, the system is checking against the original names to avoid catastrophes. Please, avoid changing the names of the programs.

I tried with a newly created user and works again.
