### ISSUE TITLE
Update Organization endpoint to allow admin to persiste thiers curreny options

### ISSUE THREAD

**Issue by bashz** [toladata/TolaActivity#1023]
on https://app.zenhub.com/workspace/o/humanitec/toladatav2/issues/752, In order to display a chosen currency and currency format, it need to be persisted first, I thought that the endpoint might be:
PUT https://dev.toladata.io/api/organization/:id/

2 additional fields are needed to be added:
currency: 3 chars
currency_format:  7 to 9 chars of digits, points, spaces and commas (e.g: "1 000,00")

Current behavior

Currency options are not saved

Expected behavior

Currencies to be saved

Steps to reproduce the behavior

    With admin role hit /activity/admin/configuration in branch feat/#752

    choose a currency

    submit your choice

Additional details

This is blocking https://app.zenhub.com/workspace/o/humanitec/toladatav2/issues/752

**Comment by karrla** [comment]
@odenypeter                        
Currency options are still no persisting

**Comment by jefmoura** [comment]
@odenypeter has confirmed with @karrla that this is already fixed.
