### ISSUE TITLE
Create CustomForm Status

### ISSUE THREAD

**Issue by jefmoura** [toladata/TolaActivity#1024]
### Story
We need to have a custom form status on Activity. With status, we can show the current situation of the custom form to users and define the behavior.

### Acceptance Criteria

GIVEN A user on Activity
WHEN they create a new custom form
THEN the status is set to new

GIVEN A user on Activity
WHEN they publish a custom form
THEN the status is set to published

GIVEN A user on Activity
WHEN they archive a custom form
THEN the status is set to archived

**Comment by mahmoodkhan** [comment]
A form can have multiple statuses at the same time. for example, it can be published and archived at the same time.

**Comment by jefmoura** [comment]
As talked to @mahmoodkhan yesterday. We gonna keep the behavior described in the story. So, a form will hold only one status.
