### ISSUE TITLE
Can not add level from the result framework

### ISSUE THREAD

**Issue by bashz** [toladata/TolaActivity#1025]
```
IntegrityError at /api/level/
duplicate key value violates unique constraint "indicators_level_pkey"
DETAIL:  Key (id)=(18) already exists.
...
...
Exception Type: IntegrityError at /api/level/
Exception Value: duplicate key value violates unique constraint "indicators_level_pkey"
DETAIL:  Key (id)=(18) already exists.

Request information:
USER: bechir

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data
```

### Current behavior
It do not create a new  Level for their Results Framework

### Expected behavior
It create a new Level

### Steps to reproduce the behavior
1. hit /activity/indicators/results-framework/:id
2. choose result framework and click on the `+`
3. Fill the form and submit

### Additional details
The bug might not appear sometime, that's due to either or not the sent id being already existent in the Database
__There is also a high chance that this is cause by a reset of an auto-increment in the database__

**Comment by jefmoura** [comment]
@bashz said that i's working great for him now.
