### ISSUE TITLE
Provide an `order` field on the level endpoit

### ISSUE THREAD

**Issue by bashz** [toladata/TolaActivity#1030]
In order to allow users to sort their result-framework we need to persist the attribute `order` on the endpoint 
PUT `https://dev.toladata.io/api/level/:id`

### Current behavior
No such field yet and the field sort (that can be confusing is used for other purposes)

### Expected behavior
Save the order field

### Steps to reproduce the behavior
create an item into the result framework

### Additional details
again :  the field sort (that can be confusing is used for other purposes)

**Comment by jefmoura** [comment]
- For what do we use the field `sort`? @bashz
- I remember that @aziz-haddad has used that field to sort a list.

**Comment by bashz** [comment]
the sort field is used for sorting among the tree on the result framework (to know levels within the tree)
While the order would sort in a linear way

**Comment by jefmoura** [comment]
Just to clarify @bashz. We're using the `sort` field as I show in the diagram and you wanna create the `order` field to use as I show in the diagram as well, right? If yes, how do you know which node is liked to which one?
![tree.png](https://images.zenhubusercontent.com/5a1557448a75884b90886d17/c4910663-6fbc-491f-9582-a207c1d6066c)

**Comment by jefmoura** [comment]
Ok. Thanks, @bashz. One of the other guys (@aziz-haddad and/or @wceolin) has to explain it to me better because I think we're not using it in the right way.

**Comment by jefmoura** [comment]
I talked to @aziz-haddad and you're right @bashz . They are using the `sort` field to sort it horizontally and they do this because they don't have the data sorted by the `parent_id` field. I'll update the endpoint, so we can fetch the data ordered. I need your help to update the frontend to remove the sort logic from there.

**Comment by jefmoura** [comment]
@odenypeter has reimplemented the Result Framework tree, so we don't need a new field anymore.

- PR with the changes: https://github.com/Humanitec/TolaDataV2/pull/1137
