### ISSUE TITLE
Staging 2.3 - add objectives not loading (backend ticket)

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#1035]
### Current behavior
Nothing happens when I click the Add button

![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/e744d931-adde-4991-ae8f-ad67f0a40a51)

### Expected behavior

The objectives should load

### Steps to reproduce the behavior

1. /activity/programs/##/objectives
2. Add Ojective
3.

**Comment by Menda** [comment]
Hi @karrla As a ProgramAdmin I can't reproduce it neither. I can add objectives and when I reload the page they are being displayed

**Comment by Menda** [comment]
Good. So waiting to be confirmed by her and getting closed 👍

**Comment by wceolin** [comment]
It should have been fixed by #948 (already deployed to staging).
