### ISSUE TITLE
Staging 2.3: Forms are not Saving: 500 error (backend)

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#1036]
### Current behavior
Saving Form causes 500 error
https://staging-activity.toladata.io/activity/forms/newform

![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/6dcc04c8-0c63-4416-95aa-1d1b8b0d893f)

**Comment by Menda** [comment]
Traceback:

```
