### ISSUE TITLE
Verify Typekit ID

### ISSUE THREAD

**Issue by AugustMiller** [toladata/TolaActivity#120]
This Typekit ID will have to match the new kit you created, @glind:

https://github.com/toladata/TolaActivity/blob/master/templates/base.html#L228

This should be updated in Tables and Work, if similar embed code is used.

**Comment by glind** [comment]
Thanks Gus.  We have actually updated the type kit ids on the mercycorps servers just not on the TolaData digital ocean servers.  Those are not really in use at the moment and will get updated in the next round of changes.
