### ISSUE TITLE
Update Indicator Form with new form fields that match the Indicator Plan for Donors

### ISSUE THREAD

**Issue by andrewtpham** [toladata/TolaActivity#266]
Based on discussions with the HQ MEL team and the wider toladata-users slack group, we are proposing to add new form fields to the Indicator Plan Form. These new fields and their definitions use the same language from our donors guidance: EC, DFID, and USAID. This will allow us to record additional data that meets our donor formats. The following fields are suggested to be added to the current form:

"Unit of Measure": ADD field between "Definition" and "Disaggregation" under the Performance tab.

"Rationale or Justification for Indicator": ADD field between "Definition" and the new "Unit of Measure" under Performance tab.

"Rationale for Target": ADD field after "LOP Target

"Means of Verification / Data Source": CHANGE field name from current spelling: "Means of verification" (including capitalization)

"Data Collection Method": CHANGE field name from the current spelling: "Data collection method" (capitalization)

"Frequency of Data Collection": ADD field after "Data Collection Method" under the Data Acquisition tab.

"Data Points": ADD field after the new "Frequency of Data Collection" field  under the Data Acquisition tab.

"Responsible Person(s) and Team": CHANGE field name from the current spelling: "Responsible person" (including capitalization).

"Method of Analysis": CHANGE field name from the current spelling: "Method of analysis" (including capitalization).

"Information User": CHANGE field name from the current spelling: "Information use" (including capitalization).

"Frequency of Reporting": CHANGE field name from the current spelling: "Reporting Frequency" (including capitalization).

"Quality Assurance Measures": ADD field after "Frequency of Reporting" field.

"Data Issues": ADD field after the new "Quality Assurance Measures" field.

"Changes to Indicator": ADD field after the new "Data Issues" field and before "Comments" field.

All form field definitions will be updated in the Form Guidance following the deployment of the new field changes.

[MC Indicator Plan Template September 2016.xlsx](https://github.com/toladata/TolaActivity/files/442075/MC.Indicator.Plan.Template.September.2016.xlsx)

**Comment by andrewtpham** [comment]
Had issues submitting ticket through TW so added directly as a Github issue.

**Comment by mahmoodkhan** [comment]
What is the purpose of the new field "Data Points"? what kind of information is going to be stored in here?

**Comment by andrewtpham** [comment]
Data Points - Some indicators may require more than one data point (FFP) to be reported or complex calculations using several data points. List all data points needed for reporting or calculation.
For example two data points that could be listed here are:
numerator: # of students graduated from course; denominator: # of students enrolled in the course (for the indicator % of graduated from training course)

**Comment by mahmoodkhan** [comment]
It sounds like what you're asking for is a composite indicator, which relies on other indicators to get its value calculated. But you're asking for a manual entry of those other indicators into a text box called "data_points", which I understand because of the need to match the donor template but our long term strategy should be developing the functionality of composite indicators whose value is auto-calculated by linking other indicators and defining their relationship.

**Comment by mahmoodkhan** [comment]
Also, the Frequency of Reporting field is already present in the Indicator form as a dropdown. So I will not be adding another one.

**Comment by karrla** [comment]
Move: "Rationale or Justification for Indicator" from Target Tab to Performance Tab place under "Unit of Measure"

Add: "Rationale for Target" under Target Tabs below "LOP Target"

**Comment by karrla** [comment]
Still missing: 

<b>Add: "Rationale for Target" under Target Tabs below "LOP Target"

**Comment by mahmoodkhan** [comment]
done
