### ISSUE TITLE
Add Distribution form to Project forms

### ISSUE THREAD

**Issue by glind** [toladata/TolaActivity#28]
<a href="https://github.com/glind"><img src="https://avatars.githubusercontent.com/u/449810?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [glind](https://github.com/glind)**
_Monday Jun 22, 2015 at 20:22 GMT_
_Originally opened as https://github.com/mercycorps/tola-activity/issues/31_

----

Create a distribution form similar to training form w/ disaggregations built in as well as individual beneficiaries through beneficiaries form.

**Comment by glind** [comment]
<a href="https://github.com/NinetteA"><img src="https://avatars.githubusercontent.com/u/13760198?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NinetteA](https://github.com/NinetteA)**
_Thursday Oct 29, 2015 at 14:45 GMT_

----

Here is the distribution form used by the Afghanistan team
https://drive.google.com/open?id=1Uicu2ffX4ghz40OSfeRZbGcViLT3I9T41EAONbY_kCk

**Comment by minedamnesia** [comment]
@karrla This is ready for testing -- I've slacked you the demo server link
