### ISSUE TITLE
Add Project Name to PI and PT Forms & Indicator Name to the Indicator Form 

### ISSUE THREAD

**Issue by glind** [toladata/TolaActivity#295]
amembaj@gmail.com from bootcamp (mbakke/Indonesia): "It would be great to have the Name (i.e. Project or Indicator) at the top of each of the tabs. For example, at the top of the Components tab, I would like to see the name of the Project, or at the top of the Indicator Summary, I would like to see the Indicator.  This helps to keep me on track so that I don't have to hunt around to find out or remind myself what Project or Indicator I am on.  I find this especially problematic when I am entering multiple Indicators or Projects at a time. "     # - from bootcamp (mbakke/Indonesia): "It would be great to have the Name (i.e. Project or Indicator) at the top of each of the tabs. For example, at the top of the Components tab, I would like to see the name of the Project, or at the top of the Indicator Summary, I would like to see the Indicator.  This helps to keep me on track so that I don't have to hunt around to find out or remind myself what Project or Indicator I am on.  I find this especially problematic when I am entering multiple Indicators or Projects at a time. "<br><br> Link to Ticket - http://127.0.0.1:8000/helpdesk/tickets/326/

**Comment by karrla** [comment]
This looks good. on the PI and PT forms could you also add the Program Name? 
If so, the Program name and the Project name may need to be on separate lines since many of the names are long. Maybe with different size fonts. Example:

<h2> Project Initiation Form </h2>
<h3>Program Name </h3>
<h5>Project Name </h5>

**Comment by glind** [comment]
No let's not add anything more, I'm not a fan of the project name even.  I already had to shorten it and reduce the size.

**Comment by karrla** [comment]
Ok, Program Name has already been added to demo server. 
Peter can you remove it? And I'll be better at vetting my requests on a ticket that is already in-dev.
