### ISSUE TITLE
Update customdashboard/public dashboard

### ISSUE THREAD

**Issue by glind** [toladata/TolaActivity#346]
Update the new indicator tab to include line charts with time based series for each indicator that shows the target vs. actual progress over time based on the actual collected date for collected data.  These should be small line charts for each indicator with one slider above that moves the time series ahead or behind based on the first collected date to the most recent collected date.

**Comment by karrla** [comment]
I like where the summary of indicators is headed, but I think leaving the base target or LOP and actuals visual is more useful than having to hover to see the numbers. 
:Current Production view
![uploads/f5115b8a-c6f3-4b3c-b98b-8ef8dbfe3aed/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff5115b8a-c6f3-4b3c-b98b-8ef8dbfe3aed%2Fblob)

New (Demo) view: 

![uploads/0f5237b0-0560-4aa2-813a-40c459cff5bf/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0f5237b0-0560-4aa2-813a-40c459cff5bf%2Fblob)

Also,  I do not see the "progress over time" in the slider
