### ISSUE TITLE
Public/Custom dashboard

### ISSUE THREAD

**Issue by glind** [toladata/TolaActivity#347]
Update the surveys section to be title evidence and pull in 2 charts for each collected data against the program indicators.  1  line chart should show the number of total responses over time (collected date) the second chart should be a break down of survey questions to responses donut chart.  Donut chart click on a response should drill down into a table showing the question and response.

**Comment by glind** [comment]
I have updated the section title as well as some of the view queries to pull in more accurate data.

**Comment by karrla** [comment]
@glind what is the status of this work? Can this be broken down into multiple tickets?

**Comment by karrla** [comment]
currently the evidence looks like. Which isn't that useful :)


![uploads/52ad6113-5872-458d-a0df-2bf1be82afe1/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F52ad6113-5872-458d-a0df-2bf1be82afe1%2Fblob)
