### ISSUE TITLE
Sortable Columns and Filterable by Activity Code

### ISSUE THREAD

**Issue by glind** [toladata/TolaActivity#37]
<a href="https://github.com/glind"><img src="https://avatars.githubusercontent.com/u/449810?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [glind](https://github.com/glind)**
_Monday Oct 26, 2015 at 08:05 GMT_
_Originally opened as https://github.com/mercycorps/tola-activity/issues/118_

---

clivingstone@cn.mercycorps.org Tate requested to have the option to sort the columns and filter by activity code within the Program Dashboard page. This would allow managers to customize the data displayed based on what is the priority for them.

**Comment by glind** [comment]
We should make the sort and filter functions reuseable as tola/util.py functions and a template include.  They will always want Program filters and for Indicator Lists (Type) and for ActivityDB Project Status

**Comment by karrla** [comment]
The Program Dashboard in Demo is not loading. So I cannot verify that this ticket is done.  See ticket: https://github.com/toladata/TolaActivity/issues/331

**Comment by odenypeter** [comment]
This ticket was addressed by creating reusable filters across various tabular reports and list pages.
