### ISSUE TITLE
Update Targets/Actuals slide graph on Home page and the Custom Dashboard Indicators tab 

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#635]
Please update the slider to show useful numbers. Right now in DEMO it only shows targets. 
Production is more useful as it shows the actuals and targets
 

![uploads/1a3b0969-2fc3-41ba-a5e2-e6718eaa09c6/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1a3b0969-2fc3-41ba-a5e2-e6718eaa09c6%2Fblob)

![uploads/8419aa0a-6937-4732-a3c0-c1f6a9136a26/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8419aa0a-6937-4732-a3c0-c1f6a9136a26%2Fblob)

Production: 

![uploads/b47a8966-5cab-483b-98db-5ab4d48564d0/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb47a8966-5cab-483b-98db-5ab4d48564d0%2Fblob)

**Comment by mahmoodkhan** [comment]
Hide the custom dashboard for now at least until it is ready for production use

**Comment by karrla** [comment]
The same feature (it is labeled target/target, not target and actuals) is broken on the Home Dashboard: 


![uploads/13c52bbd-6e47-4284-8ae5-54018320b87b/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F13c52bbd-6e47-4284-8ae5-54018320b87b%2Fimage.png)

**Comment by karrla** [comment]
The Target doesn't look right. Example DEMO - there is only one Indicator associated to the SO1 - 
SO1: Tola will be the primary system of record for managing indicators

The LOP target of that one indicator is 80
The individual data collected targets sum to 54
And the actuals sum to 54
But the slider chart shows a target of 11 303

![uploads/06f0958f-d51e-4b7b-8787-a1ece071a7ba/IMG_4053.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F06f0958f-d51e-4b7b-8787-a1ece071a7ba%2FIMG_4053.JPG)


The actuals are correct: 
![uploads/7241c165-f815-4474-9604-08fdd35cccf5/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7241c165-f815-4474-9604-08fdd35cccf5%2Fimage.png)

**Comment by mahmoodkhan** [comment]
This visualization is not showing you target vs actuals per indicator. It is per strategic objectives. That "SO1: Tola will be the primary system of record for managing indicators" is not an indicator, it is a strategic objective.

**Comment by karrla** [comment]
yes, understood, still, the target of 11 303 does not make sense.

**Comment by mahmoodkhan** [comment]
In addition to fixing the bug in calculating the total sum of targets I also fixed the indicator count. Currently it is counting number of data collection records but the UI is suggesting # of indicators so I changed it to count indicators instead.
