### ISSUE TITLE
Indicator New Data Collected UI issue

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#653]
If a user imports a new table as evidence and closes the modal, it also closes the new "New Data" collected modal

![uploads/ca5980b3-fb23-4083-891e-923bbd63b9bc/ttevidence.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fca5980b3-fb23-4083-891e-923bbd63b9bc%2Fttevidence.gif)

**Comment by karrla** [comment]
The window no longer closes, which is good, but the newly imported table does not show up in the list now. The modal needs to refresh before the table shows up in the list?

**Comment by mahmoodkhan** [comment]
This should be resolved now.

**Comment by karrla** [comment]
This is working but the Table is listed multiple times on a single import


![uploads/bf572f59-0c8a-4f82-93c8-e1aa8af20f00/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbf572f59-0c8a-4f82-93c8-e1aa8af20f00%2Fblob)
