### ISSUE TITLE
Update Breadcrumb for the Contact Form Page

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#658]
Breadcrumb for Contact Form Page ( workflow/contact_update/###/ )
Current:
Program Index / Contacts  / Contact Form

Update to:  
Program Index / Stakeholder List / Contacts / Contact Form

**Comment by karrla** [comment]
This is fixed, but the update might have broken the a few of the navigation links on the default 
/contact_add/0/ 
and the 
/contact_update/ links on the /contact_list/0/ page

First the /contact_list/0/ breadcrumbs on /contact_add/0/ page loads a 404 because it has a trailing /
/contact_list/0//

And on the /contact_list/0/ each of the /contact_update/#/ links are missing the  / at the end so they also load a 404

**Comment by mahmoodkhan** [comment]
it should be fixed now

**Comment by karrla** [comment]
If I click the New contact button on the contact list page (example: https://tola-activity-dev.mercycorps.org/workflow/contact_list/33/ )

![uploads/a706fc3c-75bd-4112-a3e3-14af08e5dcd2/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa706fc3c-75bd-4112-a3e3-14af08e5dcd2%2Fimage.png)

Then the /contact_add/ form loads correctly: https://tola-activity-dev.mercycorps.org/workflow/contact_add/33/0/

---

But the /contact_add/ form does not load from a <b> stakeholder page </b>(example: https://tola-activity-dev.mercycorps.org/workflow/stakeholder_update/33/) 

Add new contact - loads a 404

![uploads/aef7ad26-b6da-4434-9d30-86218be86c47/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Faef7ad26-b6da-4434-9d30-86218be86c47%2Fimage.png)

**Comment by mahmoodkhan** [comment]
This should be fixed now.

**Comment by karoot12** [comment]
Went to Stakeholder => Contacts => Add new contact and did not see the updated breadcrumb.

![image](https://user-images.githubusercontent.com/29285521/28243015-bd38e93e-6971-11e7-9738-57281b5f2045.png)
