### ISSUE TITLE
With Periodic Targets LOP field should be numeric only

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#661]
Once Periodic Targets (ref: #189)  are added to Indicators, the LOP Target on the Targets tab field should be numeric only
Users should also be able to define or mark that the LOP number is a percent if their indicator has a LOP targets as a percentage. 
And if the LOP is a percentage it should show as a percentage in all reports that include LOP (example: TvA report)

**Comment by mahmoodkhan** [comment]
In order to convert the text field to a number field, all of existing data must be corrected to conform to the constraints of a numeric field.

**Comment by karrla** [comment]
example data collected that needs to be cleaned up . 


![uploads/d399263f-2537-435e-9277-048e9ce44440/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd399263f-2537-435e-9277-048e9ce44440%2Fimage.png)

**Comment by glind** [comment]
Set to integer field
