### ISSUE TITLE
Dev: Quantitative Outputs Form: Add Indicator, the list of Indicators in the dropdown does not list the correct Indicators for the Program/Project. 

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#664]
Quantitative Outputs Form: Add Indicator, the list of Indicators in the dropdown does not list the correct Indicators for the Program/Project. 

![uploads/062b3652-ec29-43bc-b374-ff7ec7428586/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F062b3652-ec29-43bc-b374-ff7ec7428586%2Fblob)

**Comment by mahmoodkhan** [comment]
This bug was introduced as a result of working on GitHub issue #619
