### ISSUE TITLE
Dev: TvA Report Actuals are only in the report if collected data is Disaggregated on the Data Collected Form

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#665]
See how the 42 shows in Actuals for "Number of Indicators Results/Outcome Added", but does not list the other data collected 714 . The Actual should be 756

![uploads/9f277466-a776-428c-94b9-f41f8176796e/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9f277466-a776-428c-94b9-f41f8176796e%2Fblob)

<br>
<br>

![uploads/29b526f0-437a-404a-8a8c-0ba243ecdbab/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F29b526f0-437a-404a-8a8c-0ba243ecdbab%2Fblob)

This Data collected <br>
https://tola-activity-dev.mercycorps.org/indicators/collecteddata_update/3122
<br>
Is Disaggregated by Country

![uploads/b6393335-1363-40f3-8981-ec234d78c820/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb6393335-1363-40f3-8981-ec234d78c820%2Fblob)

https://tola-activity-dev.mercycorps.org/indicators/collecteddata_update/3264
<br> This one Is not Disaggregated

![uploads/6c49a5b3-10b8-460e-84b9-0bcfcfb91a1b/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6c49a5b3-10b8-460e-84b9-0bcfcfb91a1b%2Fblob)

**Comment by mahmoodkhan** [comment]
What should happen if someone enters data both in the Disaggregation form at the bottom and in the Achieved textbox?

**Comment by mahmoodkhan** [comment]
For now, I will pull data from the "achieved" field and not from the disaggregate data values.

**Comment by karrla** [comment]
added ticket to address/handle the disaggregations totals #667
