### ISSUE TITLE
Dev: Can't save data collected if I choose to update the achieved totals from a TolaTable

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#666]
If I choose to update the achieved totals from a TolaTable I am directed to the data collected field when I try to save. 

![uploads/22688381-f25d-4fc7-b872-628522720f34/achieved.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F22688381-f25d-4fc7-b872-628522720f34%2Fachieved.gif)

**Comment by karrla** [comment]
If I choose to update "achieved totals from table" it does not save and I do not receive the success message. 


![uploads/77d25ed1-2c55-4858-873b-e88f773fe27f/acheived totals .gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F77d25ed1-2c55-4858-873b-e88f773fe27f%2Facheived+totals+.gif)

**Comment by mahmoodkhan** [comment]
It does save it. I have not been able to replicate it on the dev server, which is where you're testing as well. Sometimes, it takes longer depending on when tole-activity receives a response from the tole-tables server. However, I added a "loading...." indicator to give users feedback that the server is busy processing the request.

**Comment by karrla** [comment]
Now saving form never completes: 

![uploads/c3aa1589-52f7-4061-8d8e-33c1eff39c67/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc3aa1589-52f7-4061-8d8e-33c1eff39c67%2Fblob)

**Comment by mahmoodkhan** [comment]
I think I found out what was going on and resolved it.
