### ISSUE TITLE
Links to the Indicators on the KPI Indicator TvA chart, load a blank Indicator Report

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#669]
![uploads/7550bb08-374f-4cfc-a6fa-a47971062371/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7550bb08-374f-4cfc-a6fa-a47971062371%2Fblob)

 Example Link from chart:

Number of Stakeholders Added

https://tola-activity-dev.mercycorps.org/indicators/data/2467/

It loads a blank report and then none of the filters work.
![uploads/41274146-d5cd-4354-bfaf-9bed6ea8d2d7/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F41274146-d5cd-4354-bfaf-9bed6ea8d2d7%2Fblob)

It should load: 

![uploads/66264d63-74d5-4473-8ce5-8ecad4a9459d/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F66264d63-74d5-4473-8ce5-8ecad4a9459d%2Fblob)

**Comment by mahmoodkhan** [comment]
This is a broken link that needs to be updated.
