### ISSUE TITLE
/project_complete_add/ form has additional fields: Program2 and Project Agreement2: 

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#678]
![uploads/84ff3309-c9aa-4484-b433-e4d8b206727a/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F84ff3309-c9aa-4484-b433-e4d8b206727a%2Fimage.png)

Once it is saved the /projectcomplete_update/ shows the correct fields: 

![uploads/fd83e825-530e-4fab-9ddb-e12bb5f71a32/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffd83e825-530e-4fab-9ddb-e12bb5f71a32%2Fimage.png)

**Comment by mahmoodkhan** [comment]
I believe this issue has been resolved as part of working on #676

**Comment by karoot12** [comment]
Tested and confirmed that "program2" "projectagreement2" no longer appears.

![image](https://user-images.githubusercontent.com/29285521/28243060-dd4ce42c-6972-11e7-9e10-45f43844105a.png)

**Comment by karoot12** [comment]
Confirmed that text is updated; @mahmoodkhan , recommend closing this ticket.

![image](https://user-images.githubusercontent.com/29285521/28389988-1bfecc54-6c8d-11e7-835a-6935bfd0ca19.png)
