### ISSUE TITLE
PT form field: Site, is not being populated from the PI form

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#679]
PT form field: Site is not being populated from the PI form

**Comment by karoot12** [comment]
Tested this item with the TolaData Reflect project, which listed the Site of Portland Mercy Corps HQ and confirmed that the site was visible on the PT form. Would like to test with multiple sites but need to have my admin rights confirmed by @mahmoodkhan

**Comment by karoot12** [comment]
Confirmed that site locations are appearing in the PT form. @mahmoodkhan, recommend closing this ticket.

![image](https://user-images.githubusercontent.com/29285521/28389878-c16a2360-6c8c-11e7-8d79-bbc9cc93c534.png)
