### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#689]
"New stakeholder" page loads 'NoneType' error

![uploads/c7d78b8d-b2f5-4157-9917-122ec643f3b3/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc7d78b8d-b2f5-4157-9917-122ec643f3b3%2Fimage.png)

![uploads/6a4a45ce-4b92-41ea-a1f2-6affef078cc5/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6a4a45ce-4b92-41ea-a1f2-6affef078cc5%2Fimage.png)

**Comment by karoot12** [comment]
Reviewed ticket and confirmed link is working in dev; added a new stakeholder and new contact with no issues (Test Case: Indonesia Training Delivery)
