### ISSUE TITLE
Upgrade Django to 1.11

### ISSUE THREAD

**Issue by mahmoodkhan** [toladata/TolaActivity#693]

**Comment by glind** [comment]
This ticket should probably be moved to the MC repo, it's very specific to the server instance.  dev-v2 and demo branches are already upgraded to Django 1.11.

**Comment by mahmoodkhan** [comment]
I created this ticket because I wanted to keep track of any code changes (commits) that were required as a a result of upgrading to Django 1.11. But I don't think I referenced it and this issue can be closed/deleted.
