### ISSUE TITLE
Dev-V2 API Post Issues for "Notes" API 

### ISSUE THREAD

**Issue by crajapax** [toladata/TolaActivity#695]
Two issues related to the Notes API:
1) the "notes" and "approvalworkflow" APIs have the same urls "http://dev-v2.tolaactivity.app.tola.io/api/notes/" 
2.) When POSTing into "notes" from the "http://dev-v2.tolaactivity.app.tola.io/api/notes/" url the following Error is returned:

ImproperlyConfigured at /api/notes/
Could not resolve URL for hyperlinked relationship using view name "notes-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.

**Comment by glind** [comment]
removed notes altogether and added API for approvalworkflow
