### ISSUE TITLE
Dev-V2 APIs with empty "create_date" and "edit_date" when POSTing

### ISSUE THREAD

**Issue by crajapax** [toladata/TolaActivity#699]
The following APIs leave "create_date" and "edit_date" empty when POSting, even when POSTing those dates. The entries stay "null".
Example:
"create_date": null,
"edit_date": null

http://dev-v2.tolaactivity.app.tola.io/api/externalservice/
http://dev-v2.tolaactivity.app.tola.io/api/externalservicerecord/
http://dev-v2.tolaactivity.app.tola.io/api/disaggregationtype/
http://dev-v2.tolaactivity.app.tola.io/api/dissagregationlabel/
http://dev-v2.tolaactivity.app.tola.io/api/disaggregationvalue/
http://dev-v2.tolaactivity.app.tola.io/api/level/
http://dev-v2.tolaactivity.app.tola.io/api/reportingfrequency/
http://dev-v2.tolaactivity.app.tola.io/api/indicatortype/
http://dev-v2.tolaactivity.app.tola.io/api/objective/

**Comment by glind** [comment]
@karrla fixed in dev please confirm in staging.
