### ISSUE TITLE
Dev V2 Pindicators API Error

### ISSUE THREAD

**Issue by crajapax** [toladata/TolaActivity#737]
FieldError at /api/pindicators/
Cannot resolve keyword 'organization' into field. Choices are: action_by, action_when, category, contingency_plan, create_date, edit_date, id, impact, likelihood, mitigation_plan, name, post_mitigation_status, rating, status, type, workflowlevel2, workflowlevel2_id

**Comment by jefmoura** [comment]
Duplicated #735

**Comment by glind** [comment]
pindicators is not used by the v2 front end but we should resolve this for CE

**Comment by Menda** [comment]
This is already solved. Closing.
