### ISSUE TITLE
Dev-V2 Beneficiary API Error

### ISSUE THREAD

**Issue by crajapax** [toladata/TolaActivity#754]
beneficiary instances are not listed in the main url "http://dev-v2.tolaactivity.app.tola.io/api/beneficiary/"

**Comment by jefmoura** [comment]
@crajapax can you check it again? The Beneficiary is filtered by workflowlevel1 organization and it wasn't being set but Rafael fixed in the PR #745, so it should work now.

**Comment by jefmoura** [comment]
It's fixed.
