### ISSUE TITLE
Retrieve Indicator endpoint permissions

### ISSUE THREAD

**Issue by Menda** [toladata/TolaActivity#794]
Story
====

Permissions document: https://docs.google.com/spreadsheets/d/1mWGhO-Acin5SQnfOrHm58UCY3Y965x98fk9i6-ozpq0/edit#gid=0

We need to fix permissions (see `IndicatorPermissions`) and add tests for /api/indicator/

Acceptance criteria
==============

GIVEN I make a GET Retrieve query to /api/indicator/
AND I have the correct permissions
THEN the Indicator is updated

**Comment by glind** [comment]
We need to clarify what permission were failing Program Admin, Org Admin etc or all on these or they are difficult to test.

**Comment by Menda** [comment]
I think we can close this. This issue was created before we even started implementing permissions. There is the "Permissions and Roles" document which can be revised by Karrla or Joy and mark and create new issues if some permission is missing.
