### ISSUE TITLE
Update WorkflowLevel1 endpoint permissions

### ISSUE THREAD

**Issue by Menda** [toladata/TolaActivity#795]
Story
====

Permissions document: https://docs.google.com/spreadsheets/d/1mWGhO-Acin5SQnfOrHm58UCY3Y965x98fk9i6-ozpq0/edit#gid=0

We need to fix permissions (see `WorkflowLevel1Permissions`) and add tests for /api/workflowlevel1/

Acceptance criteria
==============

GIVEN I make a PUT or PATCH query to /api/workflowlevel1/
AND I have the correct permissions
THEN the WorkflowLevel1 is updated

**Comment by glind** [comment]
@Menda please verify, the wording on this ticket makes it unclear what permissions were failing before.

**Comment by Menda** [comment]
I think we can close this. This issue was created before we even started implementing permissions. There is the "Permissions and Roles" document which can be revised by Karrla or Joy and mark and create new issues if some permission is missing.
