### ISSUE TITLE
Verify and clean up the use of TolaSite vs Settings in API affected areas of app

### ISSUE THREAD

**Issue by glind** [toladata/TolaActivity#820]
There are a number of areas where we use things like TolaSites to pull in configuration information as opposed to the settings from environment variables in local.py.  We need to use the settings where available and clean up the rest where they affect the API or the TolaDatav2 app.  The CE areas of the view code should continue to use TolaSites.

**Comment by Menda** [comment]
Variable: `TOLA_TRACK_URL = os.getenv('TOLA_TRACK_URL')`

**Comment by Menda** [comment]
@glind I have references to the TolaSites model in `indicators/views.py`, `customdashboard/views.py` and  `tola/views.py`. How do I know which ones are being used in the Community Edition?
