### ISSUE TITLE
Permissions: Org Admin should be able to view indicators in a program

### ISSUE THREAD

**Issue by jurzyna** [toladata/TolaActivity#845]
Program Org can only see the workflow levels but not the indicators

**Comment by joy-humanitec** [comment]
Org Admin (Leonora) still cannot see indicators for a program in her Org. She only sees the levels yest the program has 4 indicators added.

Org Admin View:
![image.png](https://images.zenhubusercontent.com/5a042a2c8a75884b9086b8e0/aa9ceb62-fc38-4200-879c-2f3d8e476c01)

Prg Admin View:
![image.png](https://images.zenhubusercontent.com/5a042a2c8a75884b9086b8e0/1cc468a6-56ec-45d0-a524-7fa0b87b88b3)
