### ISSUE TITLE
Broken link to Track after login

### ISSUE THREAD

**Issue by Menda** [toladata/TolaActivity#860]
Story
=====

After login in, when the user chooses Track it gives a 404 error because of a double dash in the URL.

`https://dev.tolatables.tola.io//login/tola`.

On the other hand, we should be flexible in the configuration and allow to set the Track URL ending with slash or without it.

Acceptance criteria
==============

GIVEN I am logged in
AND the developer set TOLA_ACTIVITY_URL ending with a slash or without it
THEN the resulting address should have just one slash

**Comment by joy-humanitec** [comment]
@Menda I am experiencing this error for some situations in Staging:

Actions: Clear cache > Login as Microsoft User OR Login as Tola > Click Track option
Result: Error

![image.png](https://images.zenhubusercontent.com/5a042a2c8a75884b9086b8e0/38e1094b-623a-4eec-8c60-dd12296c8240)

**Comment by Menda** [comment]
I can reproduce. This belongs to a different kind of bug, so I will create a new Blocker for it. If the Acceptance Criteria for this ticket is met, then we can mark this as done.
