### ISSUE TITLE
Delete method not allowed on indicators

### ISSUE THREAD

**Issue by aziz-haddad** [toladata/TolaActivity#864]
# Story

Trying to delete an indicator as a ProgramAdmin returns the following response:

`{
    "detail": "Method \"DELETE\" not allowed."
}`

# Acceptance criteria

GIVEN I am ProgramAdmin
AND I try to send a delete request for an indicator in my program
THEN the indicator should be deleted with 204 no content response back

**Comment by jefmoura** [comment]
It happens only with generated data, not with new data.

**Comment by aziz-haddad** [comment]
We find out that this is data related issue
