### ISSUE TITLE
Staging: Edit Program > Sites and  Submit -> UI breaks. 

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#878]
Staging | ProgramAdmin

Go  to Humanitarian Response in Syrain Chrisis
Click on Sites
click back on Program Edit
Click Submit

clicking on Sites: 
![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/9d898ec8-fc12-437b-b6b9-7cbcbf48075b)

**Comment by Menda** [comment]
I can't reproduce it anymore. Can you check it again, @karrla ?
