### ISSUE TITLE
Error: Track duplicate UUID error for all new *registered* users. 

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#945]
### Story (error)
A user registers for a new TolaData account, logs in and cannot access Track
Instead, they get a "silo_tolauser_tola_user_uuid_key" error

![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/5d6ee8c3-7f1e-49ec-8407-b807cf376c41)

### Acceptance Criteria

GIVEN a user registers for a new TolaData account
WHEN they log in to TolaData and click on the Track link
THEN they are logged into Track

**Comment by jefmoura** [comment]
It's an error in Track @karrla. There's a similar ticket in the Track repo, so I close this one and keep the other one.
TolaTables/[#378](https://github.com/toladata/TolaTables/issues/378)
